FunTour/Models/TravelPackageViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using FunTourDataLayer.BusCompany;
using FunTourDataLayer.EventCompany;
using FunTourDataLayer.FlightCompany;
using FunTourDataLayer.Hotel;
using FunTourDataLayer.Locality;

namespace FunTour.Models
{
    public class TravelPackageViewModel
    {
        public TravelPackageViewModel()
        {
            ReservationAmount =0;
        }
        public int Id_TravelPackage { get; set; }

        [Display(Name = "Nombre del Paquete")]
        public string PackageName { get; set; }

        [Display(Name = "Descripción del Paquete")]
        public string Description { get; set; }

        [Display(Name = "Día de Salida")]
        public DateTime FromDay { get; set; }

        [Display(Name = "Día de Llegada")]
        public DateTime ToDay { get; set; }

        [Display(Name = "Tildar si desea que el transporte sea aéreo, de lo contrario, dejar sin tildar.")]
        public bool FlightOrBus { get; set; }

        public virtual Hotel Hotel { get; set; }
        public virtual Flight ToGoFlight { get; set; }
        public virtual Flight ToBackFlight { get; set; }
        public virtual Bus ToGoBus { get; set; }
        public virtual Bus ToBackBus { get; set; }
        public virtual Event Event { get; set; }

        [Display(Name = "Cantidad de Reservaciones Posibles")]
        public int ReservationAmount { get; set; }
        public virtual City FromPlace { get; set; }
        public virtual City ToPlace { get; set; }

        [Display(Name = "Precio Total del Paquete")]
        public float TotalPrice { get; internal set; }
    }
}

FunTour/Controllers/TravelPackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FunTour.Models;
using FunTourBusinessLayer.Service;
using FunTourDataLayer.BusCompany;
using FunTourDataLayer.EventCompany;
using FunTourDataLayer.FlightCompany;
using FunTourDataLayer.Hotel;
using FunTourDataLayer.Locality;
using FunTourDataLayer.Reservation;

namespace PruebaUsers.Controllers
{
    public class TravelPackagesController : Controller
    {
        private const string AddServicesInPlaceString = "AddServicesInPlace";
        private const string AddServicesToTravelString = "AddServicesToTravel";
        private const string AddPlacesString = "AddPlaces";
        private readonly DataService Service = new DataService();

        // GET: TravelPackages
        public ActionResult Index()
        {
            return View(Service.UnitOfWork.TravelPackageRepository.Get());
        }

        // GET: TravelPackages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TravelPackage travelPackage = Service.UnitOfWork.TravelPackageRepository.GetByID(id);
            if (travelPackage == null)
            {
                return HttpNotFound();
            }
            return View(travelPackage);
        }

        // GET: TravelPackages/Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Create(int id)
        {
            var travelPackage = Service.UnitOfWork.TravelPackageRepository.Get(filter: p => p.Id_TravelPackage == id).FirstOrDefault();

            var travelPackageViewModel = new TravelPackageViewModel
            {
                Id_TravelPackage = travelPackage.Id_TravelPackage,
                PackageName = travelPackage.PackageName,
                Description = travelPackage.Description,
                FromDay = travelPackage.FromDay,
                ToDay = travelPackage.ToDay,
                FlightOrBus = travelPackage.FlightOrBus
            };
            return View(travelPackageViewModel);
        }

        // POST: TravelPackages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_TravelPackage")] TravelPackageViewModel travelPackageViewModel)
        {
            var travelPackage = new TravelPackage
            {
                Id_TravelPackage = travelPackageViewModel.Id_TravelPackage,
                PackageName = travelPackageViewModel.PackageName,
                Description = travelPackageViewModel.Description,
                FromDay = travelPackageViewModel.FromDay,
                ToDay = travelPackageViewModel.ToDay,
                FlightOrBus = travelPackageViewModel.FlightOrBus
            };

            if (ModelState.IsValid)
            {
                Service.UnitOfWork.TravelPackageRepository.Insert(travelPackage);
                Service.UnitOfWork.Save();
                return RedirectToAction(AddPlacesString, routeValues: new {travelPackageViewModel});
            }

            return View(travelPackageViewModel);
        }


        #region Places


        public ActionResult AddPlaces(TravelPackageViewModel travelPackageView)
        {
            IEnumerable<City> ListOfCityToGo = Service.UnitOfWork.CityRepository.Get(includeProperties: "Province, Country");
            IEnumerable<City> ListOfCityToStay = Service.UnitOfWork.CityRepository.Get(includeProperties: "Province, Country");


            ViewBag.FromCities = new SelectList(ListOfCityToGo, "Id_City", "Name" + "Province.Name" + "Province.Country.Name");
            ViewBag.ToCities = new SelectList(ListOfCityToStay, "Id_City", "Name" + "Province.Name" + "Province.Country.Name");

            return View();
        }

        public ActionResult AddPlacesReturn(int TravelPackageId)
        {
            var travelPackage = Service.UnitOfWork.TravelPackageRepository.Get(filter: p => p.Id_TravelPackage == TravelPackageId, includeProperties: "FromPlace, ToPlace").FirstOrDefault();

            var travelPackageViewModel = new TravelPackageViewModel
            {
                Id_TravelPackage = travelPackage.Id_TravelPackage,
                PackageName = travelPackage.PackageName,
                Description = travelPackage.Description,
                FromDay = travelPackage.FromDay,
                ToDay = travelPackage.ToDay,
                FlightOrBus = travelPackage.FlightOrBus
            };


            if (travelPackage.FromPlace != null && travelPackage.ToPlace != null && travelPackage.ToPlace != travelPackage.FromPlace)
            {
                travelPackage.ToPlace = travelPackage.ToPlace;
                travelPackage.FromPlace = travelPackage.FromPlace;
                return RedirectToAction(AddServicesToTravelString, routeValues: new { travelPackageViewModel });
            }
            return RedirectToAction(AddPlacesString, routeValues: new { travelPackageViewModel }); ;
        }

        [HttpGet]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public void AddToPlaceReturnPartialView(int CityId, int TravelPackageId)
        {
            var travelPackage = Service.UnitOfWork.TravelPackageRepository.GetByID(TravelPackageId);

            travelPackage.ToPlace = Service.UnitOfWork.CityRepository.GetByID(CityId);
            Service.UnitOfWork.TravelPackageRepository.Update(travelPackage);
            Service.UnitOfWork.Save();

        }

        [HttpGet]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public void AddFromPlaceReturnPartialView(int CityId, int TravelPackageId)
        {
            var travelPackage = Service.UnitOfWork.TravelPackageRepository.GetByID(TravelPackageId);

            travelPackage.FromPlace = Service.UnitOfWork.CityRepository.GetByID(CityId);
            Service.UnitOfWork.TravelPackageRepository.Update(travelPackage);
            Service.UnitOfWork.Save();

        }


        #endregion

        #region Bus&Flights

        public ActionResult AddServicesToTravel(TravelPackageViewModel travelPackageViewModel)
        {
            if (travelPackageViewModel.FlightOrBus)
            {
                IEnumerable<Flight> ListOfFlightsToGo = Service.GetFlights(travelPackageViewModel.FromDay, travelPackageViewModel.FromPlace, travelPackageViewModel.ToPlace);
                IEnumerable<Flight> ListOfFlightsToBack = Service.GetFlights( travelPackageViewModel.ToDay, travelPackageViewModel.FromPlace, travelPackageViewModel.ToPlace);


                ViewBag.FlightsToGo = new SelectList(ListOfFlightsToGo, "Id_Flight", "Id_Flight");
                ViewBag.FlightsToBack = new SelectList(ListOfFlightsToBack, "Id_Flight", "Id_Flight");
                ViewBag.FlighsToGoToShow = ListOfFlightsToGo;
                ViewBag.FlightsToBackToShow = ListOfFlightsToBack;
            }
            else
            {
                IEnumerable<Bus> ListOfBusesToGo = Service.GetBuses(travelPackageViewModel.FromDay, travelPackageViewModel.FromPlace, travelPackageViewModel.ToPlace);
                IEnumerable<Bus> ListOfBusesToBack = Service.GetBuses(travelPackageViewModel.FromDay, travelPackageViewModel.FromPlace, travelPackageViewModel.ToPlace);

                ViewBag.BusesToGo = new SelectList(ListOfBusesToGo, "Id_Bus", "Id_Bus");
                ViewBag.BusesToBack = new SelectList(ListOfBusesToBack, "Id_Bus", "Id_Bus");
                ViewBag.BusesToGoToShow = ListOfBusesToGo;
                ViewBag.BusesToBackToShow = ListOfBusesToBack;
            }

            return View(travelPackageViewModel);
        }

        public ActionResult AddServicesToTravelReturn(int TravelPackageId)
        {
            var travelPackage = Service.UnitOfWork.TravelPackageRepository.Get(filter: p => p.Id_TravelPackage == TravelPackageId, includeProperties:"Flight, Bus, City").FirstOrDefault();

            var travelPackageViewModel = new TravelPackageViewModel
            {
                Id_TravelPackage = travelPackage.Id_TravelPackage,
                PackageName = travelPackage.PackageName,
                Description = travelPackage.Description,
                FromDay = travelPackage.FromDay,
                ToDay = travelPackage.ToDay,
                FlightOrBus = travelPackage.FlightOrBus,
                FromPlace = travelPackage.FromPlace,
                ToPlace = travelPackage.ToPlace
            };


            if (travelPackageViewModel.FlightOrBus)
            {
                if (travelPackage.ToGoFlight != null && travelPackage.ToBackFlight != null)
                {
                    travelPackageViewModel.ToGoFlight = travelPackage.ToGoFlight;
                    travelPackageViewModel.ToBackFlight = travelPackage.ToBackFlight;
                    return RedirectToAction(AddServicesInPlaceString, routeValues: new { travelPackageViewModel });
                }

                if (travelPackage.ToGoBus != null && travelPackage.ToBackBus != null)
                {
                    travelPackageViewModel.ToGoBus = travelPackage.ToGoBus;
                    travelPackageViewModel.ToBackBus = travelPackage.ToBackBus;
                    return RedirectToAction(AddServicesInPlaceString, routeValues: new { travelPackageViewModel });
                }
            }
            return RedirectToAction(AddServicesToTravelString, routeValues: new { travelPackageViewModel }); ;
        }

        [HttpGet]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]

FunTour/Views/TravelPackages/AddPlaces.cshtml
@model FunTour.Models.TravelPackageViewModel

@{
    ViewBag.Title = "AddPlaces";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('AddPlacesReturn').click(function () {
            var _packageId = $('#Id_TravelPackage').val();

            var _parameters = { TravelPackageId: _packageId };
            $.ajax({
                url: "/TravelPackages/AddPlacesReturn",
                type: "GET",
                data: _parameters,
                success:
                    //function (data, textStatus, jqXHR) {
                    //$('#PermissionsTable').html(data);
                    //$('#PermissionId').val("");
                //}
            });
        });
    });
</script>


<h2>Lugares:</h2>

<fieldset>
    <div id="FromCity">
    </div>
    <div>
        @Html.Partial("_AddFromPlaceReturnPartialView", Model)
    </div>
    <br />

    <div id="ToCity">
    </div>
    <div>
        @Html.Partial("_AddToPlaceReturnPartialView", Model)
    </div>
    <br />


</fieldset>

@*<input type="button" id="AddPlacesReturn" value="Continuar..." />*@

@Html.ActionLink("Guardar y Continuar", "AddDataServicesToTravelReturn", new { TravelPackageId = Model.Id_TravelPackage }) |
@Html.ActionLink("Volver Atrás", "Create", new { id = Model.Id_TravelPackage })

<div>
    @Html.ActionLink("Volver al Inicio...", "Index")
</div>

FunTour/Views/TravelPackages/AddServicesInPlace.cshtml
@model FunTour.Models.TravelPackageViewModel

@{
    ViewBag.Title = "AddServicesInPlace";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('AddServicesInPlaceReturn').click(function () {
            var _packageId = $('#Id_TravelPackage').val();

            var _parameters = { TravelPackageId: _packageId };
            $.ajax({
                url: "/TravelPackages/AddServicesInPlaceReturn",
                type: "GET",
                data: _parameters,
                success:
                    //function (data, textStatus, jqXHR) {
                    //$('#PermissionsTable').html(data);
                    //$('#PermissionId').val("");
                //}
            });
        });
    });
</script>

<h2>Agregar Servicios en @Model.ToPlace.Name:</h2>

<fieldset>
    <div>
        @Html.Partial("_AddHotelToTravelPackagePartialView", Model)
    </div>
    <br />

    <div>
        @Html.Partial("_AddEventToTravelPackagePartialView", Model)
    </div>

</fieldset>

<br />

@*<input type="button" id="AddServicesInPlaceReturn" value="Guardar y Continuar..." />*@
@Html.ActionLink("Guardar y Continuar", "AddServicesInPlaceReturn", new { TravelPackageId = Model.Id_TravelPackage }) |
@Html.ActionLink("Volver Atrás", "AddServicesToTravel", new { travelPackageViewModel = Model })

<div>
    @Html.ActionLink("Volver al Menú", "Index")
</div>

FunTour/Views/TravelPackages/AddServicesToTravel.cshtml
@model FunTour.Models.TravelPackageViewModel

@{
    ViewBag.Title = "AddDataServicesToTravel";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('AddDataServicesToTravelReturn').click(function () {
            var _packageId = $('#Id_TravelPackage').val();

            var _parameters = { TravelPackageId: _packageId };
            $.ajax({
                url: "/TravelPackages/AddDataServicesToTravelReturn",
                type: "GET",
                data: _parameters
                //success:
                    //function (data, textStatus, jqXHR) {
                    //$('#PermissionsTable').html(data);
                    //$('#PermissionId').val("");
                //}
            });
        });
    });
</script>


<h2>Agregar Forma De Transporte:</h2>



@if (ViewBag.FlightOrBus)
{

    <div>
        @Html.Partial("_AddFlightToTravelPackagePartialView", Model)

    </div>
}
else
{

    <div>
        @Html.Partial("_AddBusToTravelPackagePartialView", Model)
    </div>
}
<br />
@*<input type="button" id="AddDataServicesToTravelReturn" value="Guardar y Continuar..." />*@
@Html.ActionLink("Guardar y Continuar", "AddDataServicesToTravelReturn", new { TravelPackageId = Model.Id_TravelPackage }) |
@Html.ActionLink("Volver Atrás", "AddPlaces", new { travelPackageViewModel = Model })


<div>
    @Html.ActionLink("Volver al Menú", "Index")
</div>

FunTour/Views/TravelPackages/Create.cshtml
@model FunTour.Models.TravelPackageViewModel

@{
    ViewBag.Title = "Crear Paquete Turístico";
}


@using (Html.BeginForm("Create", "TravelPackages", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.PackageName, new { @class = "col-md-2 control-label" })

        <div class="col-md-10">
            @Html.TextBoxFor(model => model.PackageName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, new { @class = "col-md-2 control-label" })

        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FromDay, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.FromDay, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ToDay, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.ToDay, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FlightOrBus, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.FlightOrBus, new { @class = "form-control" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Guardar y Continuar" />
        </div>
    </div>
}
@Html.ActionLink("Cancelar Creación", "CancelCreation", new { id = Model.Id_TravelPackage })
<div>
    @Html.ActionLink("Volver al Inicio...", "Index")
</div>

FunTour/Views/TravelPackages/Delete.cshtml
@model FunTourDataLayer.Models.TravelPackage

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TravelPackage</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Volver al Menú", "Index")
        </div>
    }
</div>

FunTour/Views/TravelPackages/Details.cshtml
@model FunTourDataLayer.Models.TravelPackage

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TravelPackage</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id_Package }) |
    @Html.ActionLink("Volver al Menú", "Index")
</p>

FunTour/Views/TravelPackages/Edit.cshtml
@model FunTourDataLayer.Models.TravelPackage

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TravelPackage</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_TravelPackage)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al Menú", "Index")
</div>

FunTour/Views/TravelPackages/Index.cshtml
@model IEnumerable<FunTourDataLayer.Models.TravelPackage>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id_TravelPackage }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id_TravelPackage }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id_TravelPackage })
        </td>
    </tr>
}

</table>

FunTour/Views/TravelPackages/_AddBusToTravelPackagePartialView.cshtml
@model FunTour.Models.TravelPackageViewModel


<script type="text/javascript">
    $(document).ready(function () {
        $('AddBus').click(function () {
            var _toGoBusId = $('#BusesToGo').val();
            var _toBackBusId = $('#BusesToBack').val();
            var _packageId = $('#Id_TravelPackage').val();

            if (_toGoBusId == '' || _toBackBusId == '') {
                return false;
            }

            var _parameters = { ToGoBusId: _toGoBusId, ToBackBusId: _toBackBusId, TravelPackageId: _packageId };
            $.ajax({
                url: "/TravelPackages/AddBusToTravelPackagePartialView",
                type: "GET",
                data: _parameters,
                success:
                    //function (data, textStatus, jqXHR) {
                    //$('#PermissionsTable').html(data);
                    //$('#PermissionId').val("");
                //}
            });
        });
    });
</script>


<h1>Colectivo de Ida</h1>>
@Html.HiddenFor(model => model.Id_TravelPackage)
<fieldset style="padding: 1em; font: 100%; color: Black; border-color: Black; border-style: solid;
    border-width: thin; border-color: Silver; width: 740px">
    <table style="width:100%">
        <tr>
            <th>ID Colectivo</th>
            <th>Fecha de Salida</th>
            <th>Fecha de Llegada</th>
            <th>Cantidad de Asientos Libres</th>
            <th>Precio</th>
        </tr>
        @foreach (FunTourDataLayer.Models.Bus item in ViewBag.BusesToGoToShow)
        {

        <tr>
            <td>@item.IdAPI_Bus</td>
            <td>@item.DateTimeArrival</td>
            <td>@item.DateTimeDeparture</td>
            <td>@item.NotReservedSeats</td>
            <td>@item.Price</td>
        </tr>
        }
    </table>

    @if (Model.ToGoBus == null)
    {
        <legend><strong>Agregar Colectivo al Paquete para ir desde @Model.FromPlace.Name hasta @Model.ToPlace:</strong></legend>

    }
    else
    {
        <a href="#">
            El colectivo asociado en este momento al paquete es:
            @Model.ToGoBus.BusCompany.Name
            @Model.ToGoBus.IdAPI_Bus
        </a>
        <legend><strong>Cambiar Colectivo Asociado al Paquetepara ir desde @Model.FromPlace.Name hasta @Model.ToPlace:</strong></legend>
    }

    @Html.DropDownList("BusesToGo", null, string.Empty, new { style = "width:350px" })

    <h1>Colectivo de Vuelta</h1>>
    <table style="width:100%">
        <tr>
            <th>ID Colectivo</th>
            <th>Fecha de Salida</th>
            <th>Fecha de Llegada</th>
            <th>Cantidad de Asientos Libres</th>
            <th>Precio</th>
        </tr>
        @foreach (FunTourDataLayer.Models.Bus item in ViewBag.BusesToBackToShow)
        {

        <tr>
            <td>@item.IdAPI_Bus</td>
            <td>@item.DateTimeArrival</td>
            <td>@item.DateTimeDeparture</td>
            <td>@item.NotReservedSeats</td>
            <td>@item.Price</td>
        </tr>
        }
    </table>

    @if (Model.ToBackBus == null)
    {
        <legend><strong>Agregar Colectivo al Paquete para volver desde @Model.FromPlace.Name a @Model.ToPlace:</strong></legend>

    }
    else
    {
        <a href="#">
            El colectivo asociado en este momento al paquete es:
            @Model.ToBackBus.BusCompany.Name
            @Model.ToBackBus.IdAPI_Bus
        </a>
        <legend><strong>Cambiar Colectivo Asociado al Paquete para volver desde @Model.FromPlace.Name a @Model.ToPlace:</strong></legend>
    }

    @Html.DropDownList("BusesToBack", null, string.Empty, new { style = "width:350px" })


    <input type="button" id="AddBus" value="Agregar Colectivos" />
</fieldset>

FunTour/Views/TravelPackages/_AddEventToTravelPackagePartialView.cshtml
@model FunTour.Models.TravelPackageViewModel

<script type="text/javascript">
    $(document).ready(function () {
        $('AddEvent').click(function () {
            var _eventId = $('#Events').val();
            var _packageId = $('#Id_TravelPackage').val();

            if (_eventId == '') {
                return false;
            }

            var _parameters = { EventId: _eventId, TravelPackageId: _packageId};
            $.ajax({
                url: "/TravelPackages/AddEventToTravelPackagePartialView",
                type: "GET",
                data: _parameters,
                success:
                    //function (data, textStatus, jqXHR) {
                    //$('#PermissionsTable').html(data);
                    //$('#PermissionId').val("");
                //}
            });
        });
    });
</script>


@Html.HiddenFor(model => model.Id_TravelPackage)
<fieldset style="padding: 1em; font: 100%; color: Black; border-color: Black; border-style: solid;
    border-width: thin; border-color: Silver; width: 740px">


    <h1>Eventes Disponibles</h1>>
    <table style="width:100%">
        <tr>
            <th>ID Evento</th>
            <th>Nombre del Evento</th>
            <th>Descripcion</th>
            <th>Cantidad de Tickets Disponibles</th>
            <th>Precio</th>
        </tr>
        @foreach (FunTourDataLayer.Models.Event item in ViewBag.EventsToShow)
        {

        <tr>
            <td>@item.Id_Event</td>
            <td>@item.Name</td>
            <td>@item.Description</td>
            <td>@item.AvailableTickets</td>
            <td>@item.Price</td>
        </tr>
        }
    </table>

    @if (Model.Event == null)
    {
        <legend><strong>Agregar Evento al Paquete</strong></legend>

    }
    else
    {
        <a href="#">
            El evento asociado en este momento al paquete es:
            @Model.Event.Name
        </a>
        <legend><strong>Cambiar Evento Asociado al Paquete:</strong></legend>
    }

    @Html.DropDownList("Events", null, string.Empty, new { style = "width:350px" })

    <input type="button" id="AddEvent" value="Agregar Evento" />
</fieldset>

FunTour/Views/TravelPackages/_AddFromPlaceReturnPartialView.cshtml
@model FunTour.Models.TravelPackageViewModel


<script type="text/javascript">
    $(document).ready(function () {
        $('AddFromCity').click(function () {
            var _cityId = $('#FromCities').val();
            var _packageId = $('#Id_TravelPackage').val();

            if (_busId == '') {
                return false;
            }

            var _parameters = { CityId: _busId, TravelPackageId: _packageId };
            $.ajax({
                url: "/TravelPackages/AddFromPlaceReturnPartialView",
                type: "GET",
                data: _parameters,
                success:
                    //function (data, textStatus, jqXHR) {
                    //$('#PermissionsTable').html(data);
                    //$('#PermissionId').val("");
                //}
            });
        });
    });
</script>


<legend><strong>Agregar Ciudad de Origen</strong></legend>

@Html.HiddenFor(model => model.Id_TravelPackage)
<fieldset style="padding: 1em; font: 100%; color: Black; border-color: Black; border-style: solid;
    border-width: thin; border-color: Silver; width: 740px">

    @Html.DropDownList("FromCities", null, string.Empty, new { style = "width:350px" })

    <input type="button" id="AddFromCity" value="Agregar Ciudad" />
</fieldset>