FunTour/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using FunTour.ActualModels;
using FunTourBusinessLayer.UnitOfWorks;
using FunTourDataLayer;
using FunTourDataLayer.AccountManagement;

namespace FunTour.Controllers
{
    [UserAuthorization]
    public class AdminController : Controller
    { 
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public AdminController()
        {
        }

        public AdminController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        private readonly UnitOfWork UnitOfWork = new UnitOfWork();

        #region FunTour

        // Muestra en el index el listado de todos los usuarios activos
        // GET: Admin
        public ActionResult Index()
        {
            // lista los usuarios activos
            // verifica si el usuario esta activo o no. los ordena primero por apellido y despues por nombre
            // List<UserDetails> UserList = _context.Database.SqlQuery<UserDetails>(string.Format("SELECT * FROM IdentityUsers p, UserDetails d WHERE p.UserName = d.UserName And(d.Inactive != 'true')", new UserDetails().LastName)).ToList();


            //List<UserDetails> UserList = (from d in _context.UserDetails
            //                              join u in _context.Users
            //                              on d.UserName equals u.UserName
            //                              where d.Inactive != true
            //                              select d).ToList();

            IEnumerable<UserDetails> UserList = UnitOfWork.UserRepository.GetUserDetails(filter : p=> p.Inactive == false);

            List < UserModel > UserModelList = new List<UserModel>();

            foreach (var item in UserList)
            {
                var auxUser = UnitOfWork.UserRepository.GetUserByUserName(item.UserName);
                    //_context.Users.FirstOrDefault(p => p.UserName == item.UserName);

                var UserModel = new UserModel
                {
                    Id_UserModel = item.Id_UserDetails.ToString(),
                    UserModelName = item.UserName,
                    LastName = item.LastName,
                    FirstName = item.FirstName,
                    IsSysAdmin = item.isSysAdmin,
                    Inactive = item.Inactive,
                    Email = auxUser.Email,
                    PhoneNumber = auxUser.PhoneNumber
                };

                UserModelList.Add(UserModel);
            }

            return View(UserModelList);
        }


        //Busca un usuario y muestra los datos
        public ViewResult UserDetails(string  IdUser)
        {
            var user = UnitOfWork.UserRepository.GetUserByID(IdUser);
                //_context.Users.FirstOrDefault(p => p.Id == IdUser);

            var User = UserModel.GetDataUserModel(user.UserName, UnitOfWork); //Ver
            SetViewBagData(IdUser);
            return View(User);
        }

        public List<SelectListItem> List_boolNullYesNo()
        {
            var _retVal = new List<SelectListItem>();
            try
            {
                _retVal.Add(new SelectListItem { Text = "Not Set", Value = null });
                _retVal.Add(new SelectListItem { Text = "Yes", Value = bool.TrueString });
                _retVal.Add(new SelectListItem { Text = "No", Value = bool.FalseString });
            }
            catch { }
            return _retVal;
        }

        private void SetViewBagData(string _UserId)
        {
            ViewBag.UserId = _UserId;
            ViewBag.List_boolNullYesNo = this.List_boolNullYesNo();
            ViewBag.RoleId = new SelectList(UnitOfWork.RolesRepository.GetRoles(orderBy: q => q.OrderBy(p => p.Name) ), "Id_Role", "RoleName");
        }

        // Toma un Model de Usuario
        [HttpPost]
        public ActionResult UserDetails(UserModel User)
        {
            if (User.UserModelName == null)
            {
                ModelState.AddModelError(string.Empty, "Invalid User Name");
            }

            if (ModelState.IsValid)
            {
                UserModel.SetDataUserModel(User, UnitOfWork);
            }
            return View(User);
        }

        public ActionResult UserCreate()
        {
            return View();
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> UserCreate(UserModel NewUser)
        {
            // controla que el usuario no haya ingresado un nombre NO valido
            if (NewUser.UserModelName == "" || NewUser.UserModelName == null)
            {
                ModelState.AddModelError(string.Empty, "El nombre de usuario es obligatorio.");
            }

            try
            {
                if (ModelState.IsValid)
                {

                    // busca una lista de nombres de usuario que coincidan con el ingresado
                    //List<string> results = (from d in _context.UserDetails
                    //                        join u in _context.Users
                    //                        on d.UserName equals u.UserName
                    //                        where d.UserName == NewUser.UserModelName
                    //                        || (d.UserName == u.UserName && u.Email == NewUser.Email)
                    //                        select d.UserName).ToList();

                    List<string> results = UnitOfWork.UserRepository.GetStringUserNames(NewUser.UserModelName, NewUser.Email);

                    bool _UserExistsInTable = (results.Count > 0);

                    UserDetails _User = null;

                    // si hay usuarios con el mismo nombre, busca el primero y si esta activo devuelve error
                    // Si el usuario no esta activo, lo activa
                    if (_UserExistsInTable)
                    {
                        
                        var Users = UnitOfWork.UserRepository.GetUserDetailsByNameEmail(NewUser.UserModelName, NewUser.Email);


                            var band = false;
                            foreach (var item in Users)
                            {
                                if (item.Inactive == false)
                                {
                                    ModelState.AddModelError(string.Empty, "El usuario ya existe!");

                                    band = true;
                                    break;
                                }
                            }
                            if (!band)
                            {
                                _User = Users.First(p => p.Inactive == true);
                                UnitOfWork.UserRepository.ActivateUserDetails(_User);
                                UnitOfWork.Save();
                                return RedirectToAction("Index");
                            }

                    }


                    // Si no hay usuarios con el mismo nombre, crea el usuario y lo almacena
                    else
                    {

                        var user = new ApplicationUser
                        {
                            UserName = NewUser.UserModelName,
                            Email = NewUser.Email
                        };


                        var result = await UserManager.CreateAsync(user, NewUser.Password);
                        if (result.Succeeded)
                        {

                            var userDetails = new UserDetails
                            {
                                FirstName = NewUser.FirstName,
                                LastName = NewUser.LastName,
                            };

                            UnitOfWork.UserRepository.CreateUserDetails(userDetails);
                            try
                            {

                                UnitOfWork.Save();
                            }
                            catch (Exception ex)
                            {

                                throw;
                            }

                        
                        //{
                        //    using (var _context = new ApplicationDbContext())
                        //    {

                        //        var userDetails = new UserDetails
                        //        {
                        //            UserName = _context.Users.FirstOrDefault(p => p.UserName == NewUser.UserModelName).UserName,

                        //            FirstName = NewUser.FirstName,
                        //            LastName = NewUser.LastName,
                        //            LastModified = System.DateTime.Now,
                        //            Inactive = false,
                        //            isSysAdmin = true
                        //        };

                        //        try
                        //        {

                        //            _context.UserDetails.Add(userDetails);
                        //            _context.SaveChanges();

FunTour/Controllers/RoleDetailsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.EntityFramework;
using FunTourDataLayer;
using FunTourDataLayer.AccountManagement;

namespace FunTour.Controllers
{
    public class RoleDetailsController : Controller
    {
        private ApplicationDbContext _context = new ApplicationDbContext();

        // GET: RoleDetails
        public ActionResult Index()
        {
            return View(_context.RoleDetails.Where(p => p.IsDeleted == false).ToList());
        }

        // GET: RoleDetails/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoleDetails roleDetails = _context.RoleDetails.Find(id);
            if (roleDetails == null)
            {
                return HttpNotFound();
            }
            return View(roleDetails);
        }

        // GET: RoleDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RoleDetails/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Role,RoleName,RoleDescription,IsSysAdmin")] RoleDetails roleDetails)
        {
            if (ModelState.IsValid)
            {
                
                _context.RoleDetails.Add(roleDetails);
                _context.SaveChanges();


                var auxrole = new IdentityRole
                {
                    Id = _context.RoleDetails.FirstOrDefault( p=> p.RoleName == roleDetails.RoleName).Id_Role.ToString(),
                    Name = roleDetails.RoleName
                };
                _context.Roles.Add(auxrole);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(roleDetails);
        }

        // GET: RoleDetails/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoleDetails roleDetails = _context.RoleDetails.Find(id);
            if (roleDetails == null)
            {
                return HttpNotFound();
            }
            return View(roleDetails);
        }

        // POST: RoleDetails/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Role,RoleName,RoleDescription,IsSysAdmin")] RoleDetails roleDetails)
        {
            if (ModelState.IsValid)
            {
                var auxrole = new IdentityRole
                {
                    Id = roleDetails.Id_Role.ToString(),
                    Name = roleDetails.RoleName
                };
                _context.Entry(auxrole).State = EntityState.Modified;
                _context.Entry(roleDetails).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(roleDetails);
        }

        // GET: RoleDetails/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoleDetails roleDetails = _context.RoleDetails.Find(id);
            if (roleDetails == null)
            {
                return HttpNotFound();
            }
            return View(roleDetails);
        }

        // POST: RoleDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            RoleDetails roleDetails = _context.RoleDetails.Find(id);
            roleDetails.IsDeleted = true;
            _context.Entry(roleDetails).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FunTour/Views/Admin/Index.cshtml
@model IEnumerable<FunTour.ActualModels.UserModel>
@{
    ViewBag.Title = "RBAC Administration";

}

<script>
    $(function () {
        $("#pbFilter").click(function () {
            $.get("/Admin/filter4FunTour", { _surname: $("#SurnameId").val() }, function (data) {
                $("#divFunTour").html(data);
            })
        })
    });

    $(function () {
        $("#pbReset").click(function () {
            $("#SurnameId").val('');
            $.get("/Admin/filterReset", {}, function (data) {
                $("#divFunTour").html(data);
            })
        })
    });

    $(document).ready(function () {
        $(":input[type='button']").button();
    });
</script>


<fieldset>
    <legend>
        <h3>
            System FunTour
        </h3>
    </legend>
    <fieldset style="font: 100%; border: Black; border-style: solid; border-width: thin; width: 30%">
        <legend><strong>Search Filter</strong></legend>
        <br />
        <div>
            <table>
                <tr>
                    <td>
                        <h3>
                            Last Name:
                        </h3>
                    </td>
                    <td>
                        @Html.TextBox("SurnameId", string.Empty, new { style = "width:200px", maxlength = 30 })

                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input type="button" value="Apply Filter" id="pbFilter" name="pbFilter" />
                        <input type="button" value="Reset" id="pbReset" />
                    </td>
                </tr>
            </table>
        </div>
    </fieldset>
    <br />
    <br />
    @Html.Partial("_ListUserTable", Model)
    <br />    
    <div>
        <input type="button" value="Create User" onclick="location.href='@Url.Action("UserCreate", "Admin")'" />
        <br />
    </div>
</fieldset>

FunTour/Views/Admin/PermissionCreate.cshtml
@model FunTourDataLayer.Models.Permission
@{
    ViewBag.Title = "Create";
}
<script type="text/javascript">
    $(document).ready(function () {
        $(":input[type='submit']").button();
        $(":input[type='text']").text();
    });
</script>
<div class="panel">
    <fieldset>
        <legend>
            <h3>
                Create Permission</h3>
        </legend>
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(true)    
            <div class="editor-label">
                @Html.LabelFor(model => model.PermissionDescription, "Permission Description")
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.PermissionDescription, new { style = "width:450px" })
                @Html.ValidationMessageFor(model => model.PermissionDescription)
            </div>          
            <br />
            <input type="submit" value="Create" />           
        }
    </fieldset>
</div>
<div>
    @Html.ActionLink("Go to Permissions", "PermissionIndex", "Admin")
</div>

FunTour/Views/Admin/PermissionDetails.cshtml
@model FunTourDataLayer.Models.Permission
@{
    ViewBag.Title = "Permission Details";
}
<script type="text/javascript">
    $(document).ready(function () {
        $(":input[type='button']").button();
    });
</script>
<div class="panel">
    <fieldset>
        <legend>
            <h3>
                Permission Details</h3>
        </legend>
        <div>
            <table style='width: 100%'>
                <tr>
                    <td style='width: 10%; font-weight: bold' class='userTable'>
                        @Html.LabelFor(model => model.PermissionDescription, "Description")
                    </td>
                    <td class='userTable'>
                        @Html.DisplayFor(model => model.PermissionDescription)
                    </td>
                </tr>                
            </table>
            <br />
            <input type="button" value="Edit Permission" onclick="location.href='@Url.Action("PermissionEdit", "Admin", new { id = Model.Id_Permission })'" />            
        </div>
        <br />
    </fieldset>    
    <div>
        <fieldset>
            <legend>
                <h3>
                    Roles Associated with this Permission</h3>
            </legend>
            <div id="RolesTable">
                @Html.Partial("_ListRolesTable4Permission", Model)
            </div>
        </fieldset>
    </div>
</div>
<div>
    @Html.ActionLink("Go to Permissions", "PermissionIndex", "Admin")  
</div>

FunTour/Views/Admin/RoleCreate.cshtml
@model FunTourDataLayer.Models.RoleDetails
@{
    ViewBag.Title = "Create Role";
}
<script type="text/javascript">
    $(document).ready(function () {
        $(":input[type='submit']").button();
        $(":input[type='button']").button();
    })
</script>
<div class="panel">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)    
        <fieldset>
            <legend>
                <h3>
                    Create Role</h3>
            </legend>
            <table style='width: 100%'>
                <tr>
                    <td style='width: 10%; font-weight: bold' class='userTable'>
                        @Html.LabelFor(model => model.RoleName)
                    </td>
                    <td style='width: 28%' class='userTable'>
                        @Html.TextBoxFor(model => model.RoleName, new { style = "width:450px" })
                        @Html.ValidationMessageFor(model => model.RoleName)
                    </td>
                    <td style='width: 8%; font-weight: bold' class='userTable'>
                        @Html.LabelFor(model => model.IsSysAdmin, "System Role")
                    <td style='width: 20%' class='userTable'>
                        @Html.EditorFor(model => model.IsSysAdmin)
                        @Html.ValidationMessageFor(model => model.IsSysAdmin)
                    </td>
                </tr>           
                <tr>
                    <td style='width: 10%; font-weight: bold' class='userTable'>
                        @Html.LabelFor(model => model.RoleDescription)
                    </td>
                    <td style='width: 28%' class='userTable'>
                        @Html.TextBoxFor(model => model.RoleDescription, new { style = "width:450px" })
                        @Html.ValidationMessageFor(model => model.RoleDescription)
                    </td>                    
                </tr>        
            </table>
            <br />
            <input type="submit" value="Create Role" />
        </fieldset>
    }
</div>
<div>
    @Html.ActionLink("Go to Roles", "RoleIndex", "Admin")
</div>

FunTour/Views/Admin/RoleDetails.cshtml
@model FunTourDataLayer.Models.RoleDetails
@{
    ViewBag.Title = "Role: " + Html.DisplayFor(model => model.RoleDescription);
}
<script type="text/javascript">
    $(function () {
        $(":input[type='button']").button();
    })
</script>
<div class="row">
    <div class="panel">
        <fieldset>
            <legend>
                <h3>
                    Role Details
                </h3>
            </legend>
            <div>
                <table style='width: 100%'>
                    <tr>
                        <td style='width: 120px;font-weight: bold' class='userTable'>
                            @Html.LabelFor(model => model.RoleName)
                        </td>
                        <td class='userTable'>
                            @Html.DisplayFor(model => model.RoleName, new { style = "width:350px" })
                            @Html.ValidationMessageFor(model => model.RoleName)
                        </td>
                    </tr>
                    <tr>
                        <td style='font-weight: bold' class='userTable'>
                            @Html.LabelFor(model => model.RoleDescription)
                        </td>
                        <td class='userTable'>
                            @Html.DisplayFor(model => model.RoleDescription, new { style = "width:90%" })
                            @Html.ValidationMessageFor(model => model.RoleDescription)
                        </td>
                    </tr>

                    <tr>
                        <td style='width: 100px; font-weight: bold' class='userTable'>
                            @Html.LabelFor(model => model.IsSysAdmin, "System Role")
                        </td>
                        <td class='userTable'>
                            @Html.DisplayFor(model => model.IsSysAdmin)
                            @Html.ValidationMessageFor(model => model.IsSysAdmin)
                        </td>
                    </tr>
                </table>
                <br />
                <input type="button" value="Edit" onclick="location.href='@Url.Action("RoleEdit", "Admin", new { id = Model.Id_Role })'" />
        </fieldset>
        <div>
            <fieldset>
                <legend>
                    <h3>
                        Permissions Associated with this Role
                    </h3>
                </legend>

                <div id="PermissionsTable">
                    @Html.Partial("_ListPermissions", Model)
                </div>
            </fieldset>
        </div>
    </div>
</div>
<br />
<div>
    @Html.ActionLink("Go to Roles", "RoleIndex", "Admin")
</div>

FunTour/Views/Admin/RoleIndex.cshtml
@model IEnumerable<FunTourDataLayer.Models.RoleDetails>
@{
  ViewBag.Title = "Roles";
}
<script type="text/javascript">
  $(document).ready(function () {
    $(":input[type='button']").button();
  });
</script>
<fieldset>
  <legend>
    <h3>
      Roles
    </h3>
  </legend>
  <table id="RoleTable" style="width: 90%">
    <thead>
    <th>
      Role Name
    </th>
    <th>
      Role Description
    </th>
    <th>
      Is System Admin
    </th>
    <th style="width: 8%">
      Action
    </th>
    </thead>
    @foreach (var item in Model)
    {
      <tr>
        <td>
          @Html.ActionLink(item.RoleName, "RoleName", new { id = item.Id_Role })
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.RoleDescription)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.IsSysAdmin)
        </td>
        <td>
          <center>
            <a href="@Url.Action("RoleEdit", "Admin", new { id = item.Id_Role })">
              <img src="@Url.Content("~/Content/Images/pen.png")" alt="Edit Role" />
            </a>
            <a href="@Url.Action("RoleDelete", "Admin", new { id = item.Id_Role })">
              <img src="@Url.Content("~/Content/Images/bin.png")" alt="Delete Role" />
            </a>
          </center>
        </td>
      </tr>
    }
  </table>
  <br />
  <div>
    <input type="button" value="Create Role" onclick="location.href='@Url.Action("RoleCreate", "Admin")'" />
    <br />
  </div>
</fieldset>
<br />
@Html.ActionLink("Go to FunTour", "Index", "Admin")

FunTour/Views/Admin/UserEdit.cshtml
@model FunTour.ActualModels.UserModel
@{
    ViewBag.Title = "User - " + Model.UserModelName;

    if ((Model.UserModelName != null) && (Model.UserModelName != ""))
    {
        ViewBag.Title = ViewBag.Title + " (" + Model.UserModelName + ")";
    }
}
<script type="text/javascript">
    $(document).ready(function () {
        $(":input[type='button']").button();
        $(":input[type='submit']").button();
    });
</script>


@using (Html.BeginForm("UserEdit", "Admin", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <input name='Id_UserModel' id='Id_UserModel' type="hidden" value="@Model.Id_UserModel" />
    <fieldset>
        <legend>
            <h3>
                User Details
            </h3>
        </legend>
        @Html.Partial("_userDetailsEdit", Model)

        <legend>
            <h3>
                Roles Associated with this User
            </h3>
        </legend>
        @foreach (var item in Model.SelectedRoles)
        {

        <div class="form-group">
            @Html.LabelFor(x => item.isSelected, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.CheckBoxFor(x => item.isSelected, new { @class = "form-control" })
            </div>
        </div>


        @*Html.HiddenFor(x => item.RoleDetails.Id_Role)*@
        @* Html.CheckBoxFor(x => item.isSelected)
        @Html.LabelFor(x => item.isSelected, item.RoleDetails.RoleName)*@
}

        @*<div class="panel" id="RolesTable">
            @Html.Partial("_ListUserRoleTable", Model)
        </div>
        @Html.Partial("_ListEditableUserRoleTable")
        <br />
        <div>
            @Html.ActionLink("Go to Roles", "RoleIndex", "Admin")
        </div>*@
        <br />
        <input type="submit" value="Save" />
    </fieldset>

    <fieldset>

    </fieldset>    
}
<br />
<div>
    @Html.ActionLink("Go to FunTour", "Index", "Admin")
</div>

FunTour/Views/Admin/_ListRolesTable4Permission.cshtml
@model FunTourDataLayer.Models.Permission
<script type="text/javascript">
    $(document).ready(function () {
        //Unbind the original image 'href' set by the controller...
        $('.deleteRole').attr('href', 'javascript://');
        $('.deleteRole').click(function () {
            $dialog.data('permissionId', $(this).attr('permissionId')).data('RoleId', $(this).attr('RoleId')).dialog("open");
        });

        var $dialog = $('<div/>')
        .html("Warning: This will remove the selected Role from this Permission.  Removing this Role may prevent FunTour from accessing areas in the application.  Only remove this Role if you intend to restrict application access.<br/><br/>Do you wish to continue?")
		.dialog({
		    autoOpen: false,
		    resizable: false,
		    height: 250,
		    modal: true,
		    title: 'Remove Role',
		    buttons: [
                        {
                            text: "Continue",
                            id: "continuebtn",
                            click: function () {
                                var _permissionId = $(this).data('permissionId');
                                var _RoleId = $(this).data('RoleId');

                                var _parameters = { permissionId: _permissionId, id: _RoleId };
                                $.ajax({
                                    url: "/Admin/DeleteRoleFromPermissionReturnPartialView",
                                    type: "GET",
                                    data: _parameters,
                                    success: function (data, textStatus, jqXHR) {
                                        $('#RolesTable').html(data);
                                    }
                                });
                                $(this).dialog('close');
                            }
                        },
                        {
                            text: "Cancel",
                            id: "cancelbtn",
                            click: function () {
                                $(this).dialog("close");
                            }
                        }]
		});
    });
</script>
@{if (Model.Roles.Count == 0)
{
    <h2><font color="red">No Associated Roles...</font></h2>
    <br />
}
else
{
    <table id="PermissionTable" style="width: 65%">
        <thead>
        <th style="width:40%">
            Role
        </th>
        <th>
            Role Description
        </th>
        <th>
            Action
        </th>
        </thead>
        @foreach (FunTourDataLayer.Models.RoleDetails Role in Model.Roles.OrderBy(u => u.RoleDescription))
        {
            <tr>
                <td>
                    @Html.ActionLink(Role.RoleName, "RoleDetails", new { id = Role.Id_Role })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Role.RoleDescription)
                </td>
                <td>
                    <center>
                        <a href="@Url.Action("DeletePermission", "Admin", new { id = Role.Id_Role, permissionId = Model.Id_Permission })" class="deleteRole" permissionid=@Model.Id_Permission Roleid=@Role.Id_Role>
                            <img src="@Url.Content("~/Content/images/bin.png")" alt="Delete Permission" />
                        </a>
                    </center>
                </td>
            </tr>
        }
    </table>
    <br />
}}